const keys = [
  // First row (14 keys)
  { label: '`', size: 'small', color: '#CCCCFF' },
  { label: '1', size: 'small', color: '#CCCCFF' },
  { label: '2', size: 'small', color: '#CCCCFF' },
  { label: '3', size: 'small', color: '#CCCCFF' },
  { label: '4', size: 'small', color: '#CCCCFF' },
  { label: '5', size: 'small', color: '#CCCCFF' },
  { label: '6', size: 'small', color: '#CCCCFF' },
  { label: '7', size: 'small', color: '#CCCCFF' },
  { label: '8', size: 'small', color: '#CCCCFF' },
  { label: '9', size: 'small', color: '#CCCCFF' },
  { label: '0', size: 'small', color: '#CCCCFF' },
  { label: '-', size: 'small', color: '#CCCCFF' },
  { label: '=', size: 'small', color: '#CCCCFF' },
  { label: 'BACKSPACE', size: 'large', color: '#FFCCCC' },

  // Second row (14 keys)
  { label: 'TAB', size: 'medium', color: '#FFCCCC' },
  { label: 'Й', size: 'small', color: '#CCFFCC' },
  { label: 'Ц', size: 'small', color: '#CCFFCC' },
  { label: 'У', size: 'small', color: '#CCFFCC' },
  { label: 'К', size: 'small', color: '#CCFFCC' },
  { label: 'Е', size: 'small', color: '#CCFFCC' },
  { label: 'Н', size: 'small', color: '#CCFFCC' },
  { label: 'Г', size: 'small', color: '#CCFFCC' },
  { label: 'Ш', size: 'small', color: '#CCFFCC' },
  { label: 'Щ', size: 'small', color: '#CCFFCC' },
  { label: 'З', size: 'small', color: '#CCFFCC' },
  { label: 'Х', size: 'small', color: '#CCFFCC' },
  { label: 'Ї', size: 'small', color: '#CCFFCC' },
  { label: '\\', size: 'small', color: '#CCFFCC' },

  // Third row (13 keys)
  { label: 'CAPS', size: 'medium', color: '#FFCCCC' },
  { label: 'Ф', size: 'small', color: '#FFFFCC' },
  { label: 'І', size: 'small', color: '#FFFFCC' },
  { label: 'В', size: 'small', color: '#FFFFCC' },
  { label: 'А', size: 'small', color: '#FFFFCC' },
  { label: 'П', size: 'small', color: '#FFFFCC' },
  { label: 'Р', size: 'small', color: '#FFFFCC' },
  { label: 'О', size: 'small', color: '#FFFFCC' },
  { label: 'Л', size: 'small', color: '#FFFFCC' },
  { label: 'Д', size: 'small', color: '#FFFFCC' },
  { label: 'Ж', size: 'small', color: '#FFFFCC' },
  { label: 'Є', size: 'small', color: '#FFFFCC' },
  { label: 'ENTER', size: 'medium', color: '#FFCCCC' },

  // Fourth row (12 keys)
  { label: 'SHIFT', size: 'large', color: '#FFCCCC' },
  { label: 'Я', size: 'small', color: '#FFCCFF' },
  { label: 'Ч', size: 'small', color: '#FFCCFF' },
  { label: 'С', size: 'small', color: '#FFCCFF' },
  { label: 'М', size: 'small', color: '#FFCCFF' },
  { label: 'И', size: 'small', color: '#FFCCFF' },
  { label: 'Т', size: 'small', color: '#FFCCFF' },
  { label: 'Ь', size: 'small', color: '#FFCCFF' },
  { label: 'Б', size: 'small', color: '#FFCCFF' },
  { label: 'Ю', size: 'small', color: '#FFCCFF' },
  { label: '.', size: 'small', color: '#FFCCFF' },
  { label: 'SHIFT', size: 'large', color: '#FFCCCC' }
];
